[package]
name = "mlog"
version = "0.1.0"
authors = ["Mike Yagley <myagley@gmail.com>"]
edition = "2018"

[dependencies]
byteorder = "1"
failure = "0.1"

[dev-dependencies]
quickcheck = "0.8"
quickcheck_macros = "0.8"
